version: '3'

services:
     web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/app
        ports:
        - "8000:8000"

        #  docker-compose run web django-admin startproject pro cmd to run to create project and run docker-compose at same time